target_semester_income: 47750
months_per_semester: 5

standard_rates:
  single: 1005
  double: 805

rooms:
  1:
    type: double
  2:
    type: double
  3:
    type: double
  4:
    type: single
  5:
    type: double
  6:
    type: single
  7:
    type: single
    custom_rate: 1105

tenants:
  1:
    - Thompson
    - Charles
  2:
    - Manny
    - Bryan
  3:
    - Pine
    - JP
  4:
    - Eddie
  5:
    - Arquime
    - Nathan
  6:
    - Richard
  7:
    - Alex
